version: '3'
services:
  api:
    build:
      context: '.'
      dockerfile: './backend/Dockerfile'
    container_name: 'api-portfolio-password-manager'
    ports:
      - '${API_PORT:-3001}:3001'
    volumes:
      - './backend:/usr/src/app'
    environment:
      NODE_ENV: 'development'
    command: 'npm run dev'
  app:
    build:
      context: '.'
      dockerfile: './frontend/Dockerfile'
    container_name: 'portfolio-password-manager'
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - './frontend:/usr/src/app'
    environment:
      NODE_ENV: 'development'
    command: 'npm run dev'
