version: '3'
services:
  app:
    build:
      context: '.'
    container_name: 'portfolio-frontend-password-manager'
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - '.:/usr/src/app'
    environment:
      NODE_ENV: 'development'
    command: 'npm run dev'
